/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_jni_Demo */

#ifndef _Included_com_example_jni_Demo
#define _Included_com_example_jni_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_Demo
 * Method:    sayhello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring
extern "C" jstring Java_com_example_jni_Demo_sayhello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
